name: Photodagger.com
favicon: null
layout_spectrum: 0.854731212137267
typography_spectrum: 0.8002751874737442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.12647464033216238
  lightness: 0.20907914428971708
  saturation: 0.7826408634427935
  rhythmicContrast: 0.04430594248697162
purpose: []
